// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://efggahyzzlvgvhviblhn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVmZ2dhaHl6emx2Z3ZodmlibGhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5Mjk2NzcsImV4cCI6MjA1ODUwNTY3N30.leczbZcbTawRgT9iDwRJsLGfMZFZiv_rygHah8SV3EA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);